config/routes.rb
AuthenticationWithSorcery::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  get "secret" => "home#secret", :as => "secret"
  root 'home#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_authenticated
  	redirect_to login_url, :alert => "First login to access this page."
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :require_login, :only => :secret
  def index
  end

  def secret
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end
	
  def create
  	user = login(params[:email], params[:password], params[:remember_me])
  	if user
    	redirect_back_or_to root_url, :notice => "Logged in!"
  	else
    	flash.now.alert = "Email or password was invalid"
    	render :new
  	end
	end

	def destroy
  	logout
  	redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
  	@user = User.new
	end

	def create
  	@user = User.new(user_params)
  	if @user.save
	    redirect_to root_url, :notice => "Signed up!"
  	else
    	render :new
  	end
	end

	private
  
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :created_at, :updated_at, :salt)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Welcome</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p><%= link_to "Visit secret page", secret_path %></p>

app/views/home/secret.html.erb
<h1>This is secret!</h1>
<p>Shhh, don't tell anyone.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthenticationWithSorcery</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="container">
		<div class="user_nav">
			<% if current_user %>
  			Logged in as <%= current_user.email %>.
  			<%= link_to "Log out", logout_path %>
			<% else %>
  			<%= link_to "Sign up", signup_path %> or
  			<%= link_to "log in", login_path %>.
			<% end %>
		</div>
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %>
		<%= yield %>	
	</div>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up </h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>